---
title: "Re-Analysis of GSE21755"
author: "Dave Bridges"
date: "May 20, 2015"
output:
  html_document:
    keep_md: yes
  pdf_document:
    keep_tex: yes
---

```{r global_options, include=FALSE}
library(knitr)
opts_chunk$set(fig.path='figure/',
               echo=FALSE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
```

This is generated via GEO2R based on the Duvel et al paper.

```{r geo2r, results='asis'}
# Version info: R 2.14.1, Biobase 2.15.3, GEOquery 2.23.2, limma 3.10.1
# R scripts generated  Wed May 20 14:03:38 EDT 2015

################################################################
#   Differential expression analysis with limma
library(Biobase)
library(GEOquery)
library(limma)

# load series and platform data from GEO

gset <- getGEO("GSE21755", GSEMatrix =TRUE)
if (length(gset) > 1) idx <- grep("GPL1261", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

# make proper column names to match toptable 
fvarLabels(gset) <- make.names(fvarLabels(gset))

# group names for all samples
sml <- c("G0","G0","G0","G1","G1","G1","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X");

# eliminate samples marked as "X"
sel <- which(sml != "X")
sml <- sml[sel]
gset <- gset[ ,sel]

# log2 transform
ex <- exprs(gset)
qx <- as.numeric(quantile(ex, c(0., 0.25, 0.5, 0.75, 0.99, 1.0), na.rm=T))
LogC <- (qx[5] > 100) ||
          (qx[6]-qx[1] > 50 && qx[2] > 0) ||
          (qx[2] > 0 && qx[2] < 1 && qx[4] > 1 && qx[4] < 2)
if (LogC) { ex[which(ex <= 0)] <- NaN
  exprs(gset) <- log2(ex) }

# set up the data and proceed with analysis
fl <- as.factor(sml)
gset$description <- fl
design <- model.matrix(~ description + 0, gset)
colnames(design) <- levels(fl)
fit <- lmFit(gset, design)
cont.matrix <- makeContrasts(G1-G0, levels=design)
fit2 <- contrasts.fit(fit, cont.matrix)
fit2 <- eBayes(fit2, 0.01)
tT <- topTable(fit2, adjust="fdr", sort.by="B", number=250)

# load NCBI platform annotation
gpl <- annotation(gset)
platf <- getGEO(gpl, AnnotGPL=TRUE)
ncbifd <- data.frame(attr(dataTable(platf), "table"))

# replace original platform annotation
tT <- tT[setdiff(colnames(tT), setdiff(fvarLabels(gset), "ID"))]
tT <- merge(tT, ncbifd, by="ID")
tT <- tT[order(tT$P.Value), ]  # restore correct order

tT <- subset(tT, select=c("ID","adj.P.Val","P.Value","t","B","logFC","Gene.symbol","Gene.title"))
write.table(tT, file=stdout(), row.names=F, sep="\t")

################################################################
#   Boxplot for selected GEO samples
library(Biobase)
library(GEOquery)

# load series and platform data from GEO

gset <- getGEO("GSE21755", GSEMatrix =TRUE)
if (length(gset) > 1) idx <- grep("GPL1261", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

# group names for all samples in a series
sml <- c("G0","G0","G0","G1","G1","G1","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X","X")

# eliminate samples marked as "X"
sel <- which(sml != "X")
sml <- sml[sel]
gset <- gset[ ,sel]

# order samples by group
ex <- exprs(gset)[ , order(sml)]
sml <- sml[order(sml)]
fl <- as.factor(sml)
labels <- c("WT","KO")

# set parameters and draw the plot
palette(c("#dfeaf4","#f4dfdf", "#AABBCC"))
dev.new(width=4+dim(gset)[[2]]/5, height=6)
par(mar=c(2+round(max(nchar(sampleNames(gset)))/2),4,2,1))
title <- paste ("GSE21755", '/', annotation(gset), " selected samples", sep ='')
boxplot(ex, boxwex=0.6, notch=T, main=title, outline=FALSE, las=2, col=fl)
legend("topleft", labels, fill=palette(), bty="n")

#write to output file
output_file <- '../data/processed/GSE21755 Analysis.csv'
write.fit(fit2, file=output_file, adjust='BH')

sig.results <- droplevels(topTable(fit2, p.value=0.05, n=Inf, adjust.method="BH"))
#annotate the probes
sig.duvel.genes <- unique(levels(sig.results$Gene.Symbol))

mTsc.datafile <- '../data/processed/Binary DESeq Results.csv'
mtsc.data <- read.csv(mTsc.datafile)
sig.mtsc.data <- droplevels(subset(mtsc.data, padj<0.05))

sig.mtsc.genes <- sig.mtsc.data$external_gene_name
sig.overlap <- intersect(sig.duvel.genes, sig.mtsc.genes)
```

Duvel et al identified `r length(sig.duvel.genes)` in their analysis out of a total of `r length(levels(fit2$genes$Gene.Symbol))` genes assessed.  Of these differentially expressed genes. `r length(sig.overlap)` genes overlapped with our `r dim(sig.mtsc.data)[1]` significantly different genes.

```{r duvel-mtsc-venn}
require(venneuler)
v.diseases <- venneuler(c("Tsc2 Knockout MEFs"=length(sig.duvel.genes), 
                 "Tsc1 Knockout Muscles"=length(sig.mtsc.genes),
                 "Tsc2 Knockout MEFs&Tsc1 Knockout Muscles"=length(intersect(sig.duvel.genes, sig.mtsc.genes))))

plot(v.diseases, main="TSC-Dependent Transcriptional Changes")

library(Vennerable)
v.list <- list(`Tsc2 Knockout MEFs` = sig.duvel.genes, `Tsc1 Knockout Muscles` = sig.mtsc.genes)
v.data <- Venn(v.list)
plot(v.data)
```

```{r session-info}
sessionInfo()
```